### ISSUE TITLE
`bash` is not always available

### ISSUE THREAD

**Issue by alexgorbatchev** [Angelinsky7/Docker-Volume-Watcher#7]
I'm trying to debug why sometimes watching doesn't work for me. I have a couple of notes/thoughts:

1. There's really no way to tell where the "disconnect" is when my docker watchers aren't firing. Is it the volume watcher not doing its job or do I have something broken? I log UI would help with that.
2. I found in the code `Cmd = new string[] { "bash", "-c", $"chmod $(stat -c %a {dockerPath}) {dockerPath}" },`. If i'm reading it correctly, it uses container's `bash` to execute `chmod`. Many containers don't offer `bash` by default, most commonly those derived from `Alpine`, which is a very common base for minimal containers. I suggest changing `bash` to `sh` or possibly trapping the call and doing a fallback if it fails.

In general, as a "wish", I would've preferred this whole utility to be a console app with ability to pass config file in and watch only specific containers. It would probably also make development less complicated :)

**Comment by Angelinsky7** [comment]
> There's really no way to tell where the "disconnect"

You can always look into the event viewer.

>  I suggest changing bash to sh or possibly trapping the call and doing a fallback if it fails.

Yes i use bash, and it's maybe a bad idea. i'll look to use sh instead...

I made the app like that because i dind't want to use a console app !!! For me, it should be a feature that Window/Cifs/Docker devs should have done... But neither of them want to do the changes....
It should be automatic, invisible and without any user interaction.
Sadly it's not totally possible. If you prefere the console app, there is project like that (https://github.com/merofeev/docker-windows-volume-watcher) that already do the job pretty well.

> with ability to pass config file in and watch only specific containers

and for the case with the options "Only watch containers that have a dvwingore file" this is already the case.

**Comment by Angelinsky7** [comment]
I'll will add the possibility to choose between bash and sh for now in the ui.
When done, if you can tell me if you still have the watching issues it would be great !

**Comment by Angelinsky7** [comment]
a new version is available, let me know : https://github.com/Angelinsky7/Docker-Volume-Watcher/releases/tag/0.0.9.0
Be aware, the auto updater was "broken" you need to exit the tray app by hand (right click on the icon and the quit) to launch the update

**Comment by Angelinsky7** [comment]
no news so closed
