### ISSUE TITLE
Cannot connect to docker deamon

### ISSUE THREAD

**Issue by NaLLiFFuNT** [Angelinsky7/Docker-Volume-Watcher#8]
Unfortunately, this won't work out for me. I've found in event log following

> 

Имя журнала:   Docker Volume Watcher
Источник:      DockerVolumeWatcherSource
Дата:          30.10.2017 7:09:13
Код события:   0
Категория задачи:Отсутствует
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     Мр-ПК
Описание:
Cannot connect to docker deamon: Время ожидания операции истекло.

`Cannot connect to docker deamon: Operation timed out`

what do i do wrong?

**Comment by DSinkov** [comment]
Got the same issue on windows 10
>
 Log Name:      Docker Volume Watcher
Source:        DockerVolumeWatcherSource
Date:          10/30/2017 12:29:33 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN-L9PO57HVELF
Description:
Cannot connect to docker deamon: Docker API responded with status code=InternalServerError, response=A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Angelinsky7** [comment]
hi,
Can you first update the docker volume watcher version with this new one : https://github.com/Angelinsky7/Docker-Volume-Watcher/releases/tag/0.0.10.0

I corrected a nasty bug that make the watcher unusable and i added a properties to set the docker endpoint.
by default it's : npipe://./pipe/docker_engine but if you active the "expose deamon on tcp:....." options in docker and change the docker endpoint to "tcp://localhost:2375" it'll maybe work for both of you...

https://docs.docker.com/docker-for-windows/faqs/#how-do-i-connect-to-the-remote-docker-engine-api

This is very strange that the named pipe doesn't work, is your docker up to date ?

you can check if the pipe is open : https://stackoverflow.com/questions/258701/how-can-i-get-a-list-of-all-open-named-pipes-in-windows#258825

```
pipelist64.exe | grep docker
dockerLogs                                        1               -1
dockerBackend                                     1               -1
docker_d4w_systray                                5               -1
PSHost.131538276580267024.3508.DefaultAppDomain.com.docker.service          1                1
dockerDataBase                                    3               -1
dockerMobyLinuxVM-com1                            1                1
dockerVpnKitDiagnostics                           4               -1
docker_engine                                     2               -1
```

**Comment by Angelinsky7** [comment]
closed because no news
